### ISSUE TITLE
Bylines and other secondary is now black on white

### ISSUE THREAD

**Issue by NattyNarwhal** [lobsters/lobsters#1445]
Looks this way in Firefox and Safari:

![Image](https://github.com/user-attachments/assets/db8ff935-b814-40c0-8998-406cfedb811a)

![Image](https://github.com/user-attachments/assets/a47c800e-5b48-4e7c-8ab7-695fafb785ce)

May be a regression from #1410; cc @rahul1990gupta

**Comment by NattyNarwhal** [comment]
Browser and system settings are set to light mode. If I set it to dark mode, it goes to hard white on black.

**Comment by NattyNarwhal** [comment]
In light mode, the bylines/domains/usernames/etc used to be a dark grey colour instead of black; in light mode the luma is inverted so bylines were light grey instead of white. I can't stand up an instance of the site right now from before, but if you look at issues with screenshots prior to the PR being merged (i.e. [this one](https://github.com/lobsters/lobsters/issues/1430#issue-2779205317)), it shows what it looks like in dark mode at least.

**Comment by sknebel** [comment]
You can check the old styling on archive.org, e.g. (random example) https://web.archive.org/web/20250103083142/https://lobste.rs/s/evkrdq/who_s_hiring_q1_2025

Comparing the two with devtools, it seems (in dark mode) the transparency used to darken elements got lost in the CSS rework, and it is thus almost-white instead of almost-white and 61% transparent.

**Comment by rahul1990gupta** [comment]
Thanks. 
Most likely, I css nested functions `rgba` and rgb are not playing nice with each other here. 
https://github.com/lobsters/lobsters/blob/master/app/assets/stylesheets/application.css#L113-L122

```
	--color-fg: rgba(var(--palette-fg), var(--opacity-contrast-15)); /* primary text */
	--color-fg-contrast-13: rgba(var(--palette-fg), var(--opacity-contrast-13));
	--color-fg-contrast-10: rgba(var(--palette-fg), var(--opacity-contrast-10));
	--color-fg-contrast-7-5: rgba(var(--palette-fg), var(--opacity-contrast-7-5));
	--color-fg-contrast-6: rgba(var(--palette-fg), var(--opacity-contrast-6));
	--color-fg-contrast-5: rgba(var(--palette-fg), var(--opacity-contrast-5));
	--color-fg-contrast-4-5: rgba(var(--palette-fg), var(--opacity-contrast-4-5));

	--color-fg-gradient-lit: rgba(var(--palette-fg), var(--opacity-gradient-lit));
	--color-fg-gradient-shadowed: rgba(var(--palette-fg), var(--opacity-gradient-shadowed)); /* d7d7d7 */
```

```
	--palette-bg: light-dark(rgb(254, 254, 254), rgb(12, 12, 12));
	--palette-fg: light-dark(rgb(51, 51, 51), rgb(225, 225, 225));
	--palette-light: rgb(255, 255, 255);
	--palette-shadow: rgb(0, 0, 0);

	/* blends of foreground color over the background */
	--opacity-contrast-15: light-dark(100%, 87%); /* Contrast capped at 10:1 for dark mode */
	--opacity-contrast-13: light-dark(94%, 87%);
	--opacity-contrast-10: light-dark(84%, 87%);
	--opacity-contrast-7-5: light-dark(75%, 77%);
	--opacity-contrast-6: light-dark(67%, 69%);
	--opacity-contrast-5: light-dark(63%, 64%);
	--opacity-contrast-4-5: light-dark(59%, 61%); /* WCAG AA minimum 4.5:1 text contrast */

	--opacity-gradient-lit: light-dark(0%, 13%);
	--opacity-gradient-shadowed: light-dark(13%, 3%);
```

**Comment by pushcx** [comment]
I spent a minute tinkering. It's some kind of validation issue. https://jigsaw.w3.org/css-validator/validator?uri=Lobste.rs%2Fassets%2Fapplication-14dd2bf2.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

But I've pasted [samples into the validator](https://jigsaw.w3.org/css-validator/#validate_by_input) to get a small testcase and I can't reproduce it.

```

:root {
  --pallette-bg: pink;
  --pallette-fg: light-dark(green, orange);
}

html {
  --test-a: var(--pallette-bg);
  --test-b: var(--pallette-fg);
}

```

At this point I wonder if there's some character encoding problem, like a `-` is replaced with an emdash. I can't check those with the device I have now.

**Comment by pushcx** [comment]
The validation error is a little misleading here. The css `rgba` requires four args. The `--pallette-bg` variable used to be three numbers, so the call in `html` would expand to `rgba(254, 254, 254, 50%)` which is valid.

After the PR, the variable is set to `light-dark(rgb(254, 254, 254), rgb(12, 12, 12))` which evaluates to a color, so the `html` call becomes `rgba(rbg(254, 254, 254), 50%)` or `rgba(#fefefe, 50%)` (I'm not sure which, both are invalid and produce the same validation error).

I am going out to dinner so I can't figure out the fix, but this is the cause.

**Comment by Summertime** [comment]
```css
:root {
  background-color: rgba(from var(--var) r g b / 50%) 
}
```

Would probably be the easiest and cleanest fix, if it didn't land less than a year ago.

**Comment by pushcx** [comment]
Some of the ([many](https://lobste.rs/s/o2hhjc/what_happened_text_colour)) reporters have confirmed this is fixed by @clemeth's PR. Thank you!

**Comment by xonixx** [comment]
Still broken on iPad / iPhone

![Image](https://github.com/user-attachments/assets/ac2c274f-8a51-4089-8822-377eba9c5ca3)

![Image](https://github.com/user-attachments/assets/65710fed-de65-41c7-81a6-09d5f68122c9)

**Comment by clemeth** [comment]
@xonixx If you are able to update your browser, it should be fine on the latest mobile Safari.

There are more [reports on Lobsters](https://lobste.rs/s/o2hhjc/what_happened_text_colour#c_vm7x8q) of users experiencing the same. It is because of the `light-dark` color function (428034d), which isn't supported in older browsers (and AFAIK not in the latest version of qutebrowser either, the users of which I assume are overrepresented in the Lobsters crowd).

If this is an issue that affects many, it is also an option to refactor back to using regular `@media` queries.

**Comment by xonixx** [comment]
@clemeth I'm glad to but I own rather old iPhone / iPad, so not sure I can.

**Comment by pushcx** [comment]
https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Flobste.rs%2Fassets%2Fapplication-538fc68d.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

There's still some invalid code. Safari + Firefox accept it. Chrome doesn't.

Maybe reintroduced by #1449? I'm at my desktop so I have full debugging tools again, but I don't have time to look until [office hours](https://push.cx/stream). If someone wants to PR it I can merge + deploy that, though.

**Comment by clemeth** [comment]
@pushcx It should be valid CSS. I believe the validator is out of date and doesn't support variables.

**Comment by pushcx** [comment]
It does in the example I posted above trying to narrow down the problem.

**Comment by pushcx** [comment]
I can't repro this in mobile Safari, Chromium, or Firefox.

If you see the wrong text color or a box instead of an upvote arrow, please reopen. Include your browser, platform, and a screenshot of the `color`  property for the element (dev tools -> inspect element -> select 'Computed' tab).

**Comment by clemeth** [comment]
Apologies, I wrote the wrong thing. It supports variables, but rejects functions (`light-dark` and `color-mix` in our case). The validation errors start with 428034d, which introduces the former.

Running [this gist](https://gist.github.com/clemeth/3a0956258781a4a05fcbcb8565542f4d) through the validator might serve as confirmation.

**Comment by clemeth** [comment]
This is what it looks like in qutebrowser: ![Image](https://github.com/user-attachments/assets/0bc34345-2068-492a-99a3-7c1434d13f86)

Removing `light-dark` from `--color-fg-shape` fixes the upvote arrow: ![Image](https://github.com/user-attachments/assets/40285aa1-320f-4aad-aa9a-ec87b2c4c0a5)

**Comment by xonixx** [comment]
![Image](https://github.com/user-attachments/assets/00f7d43b-faa7-41d3-a5ac-37b33f842745)

![Image](https://github.com/user-attachments/assets/7ccd917f-156b-45f5-84c3-977b5694abeb)

![Image](https://github.com/user-attachments/assets/e0624481-45e7-4dc4-9c1b-bc2cf5c5ac8e)

**Comment by pushcx** [comment]
@clemeth Thanks for helping diagnose what's invalid in the css. I know it's a slog to iterate with the validator.

**Comment by clemeth** [comment]
@pushcx Amazingly, it seems the validator was updated overnight to start supporting the `light-dark` function. The link in [your earlier comment](https://github.com/lobsters/lobsters/issues/1445#issuecomment-2615976526) now only shows a few errors related to `color-mix`. I am certain that the syntax is correct here as well, and believe they will be resolved with another validator update.

There is also an error in `form.disowner-form` which is from c99c6c3 and looks valid to me ([CSS Nesting Module](https://drafts.csswg.org/css-nesting-1/)).

**Comment by pushcx** [comment]
@clemeth You're right. I found their issue tracking the work: https://github.com/w3c/css-validator/issues/421

**Comment by clemeth** [comment]
@pushcx I have [a branch](https://github.com/clemeth/lobsters/tree/fix/light-dark-compat) ready that reverts to the regular `prefers-color-scheme` approach + some minor refactoring (including removing `color-mix` since then it won't be needed). As you mention, it requires some duplicate code.

Nevertheless, whether to have extended compatiblity with outdated/niche browsers or to use the most modern CSS is something to consider.

**Comment by pushcx** [comment]
I'd immediately merge a solution that didn't have duplication, but otherwise I'd like to leave this open a while in the hopes an affected user will contribute to a better fix.

**Comment by pushcx** [comment]
I've deployed @clemeth's fix and (once again) think the bug is fixed. Please reopen if you can reproduce.

**Comment by xonixx** [comment]
Nice! Fixed for my cases! Thank you @pushcx @clemeth !
